[[main]]
name = "About"
url = "/#about"
weight = 20

[[main]]
name = "Skills"
url = "/#skills"
weight = 30

[[main]]
name = "Experience"
url = "/#experience"
weight = 40

[[main]]
name = "Tech Stack"
url = "/#technical"
weight = 45

[[main]]
name = "Screenshots"
url = "/#screenshots"
weight = 47

[[main]]
name = "Contact"
url = "/#contact"
weight = 50

